### ISSUE TITLE
Error with internal parse_factor function when using build_report

### ISSUE THREAD

**Issue by adroghini** [dpseidel/stmove#38]
I tried running the build_report function using the AG195_final test dataset. The report did not complete and gave me the following error message:
 
Quitting from lines 59-99 (report.Rmd) 
Error in parse_factor(paste(lubridate::month(date, label = TRUE), lubridate::year(date)),  : 
  could not find function "parse_factor"

(As well as some warning messages):
In addition: Warning messages:
1: Removed 1 rows containing non-finite values (stat_bin). 
2: Removed 13 rows containing non-finite values (stat_bin).

**Comment by dpseidel** [comment]
`parse_factor` is a function from the readr package. This suggests readr needs to be listed as a dependency or better yet, I should use the `as_factor` function in forcats instead - as it is already a listed dependency. 

In the meantime, you should be able to remove this error by installing and loading the readr package.

**Comment by adroghini** [comment]
Loading readr worked to resolve that error- simple solution! Thank you. I did get another error when trying to compile the report, but let me open up another issue for that.

**Comment by adroghini** [comment]
Not sure if it's worth opening up another issue since it's an easy fix- but tinytex also needs to be listed as a required dependency. For some reason, my computer came up with all kinds of issues trying to install it e.g. needing to install Rtools, etc. But once it was installed the report compiled just fine.

I also noticed that the patchwork package needed to be installed (maybe for the kalman function)? I don't think it's currently listed as a required package in the vignette.
